version: "3.8"
services:
  postgres:
    image: postgres:16
    container_name: postgres-notes
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: notepad
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - notepad-net

  redis:
    image: redis:7
    container_name: redis-notes
    ports:
      - "6379:6379"
    networks:
      - notepad-net

volumes:
  pgdata:

networks:
  notepad-net: